  # https://github.com/actions/create-release/issues/14

name: Create release when appropriately tagged and upload builds
on: push
defaults:
  run:
    shell: bash

jobs:
  release:
    name: Create release and provide URL to it
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Output Release URL File
        run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
      - name: Save Release URL File for publish
        uses: actions/upload-artifact@v1
        with:
          name: release_url
          path: release_url.txt

  publish:
    if: contains(github.ref, 'tags/v')
    needs: release
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Load Release URL File from release job
        uses: actions/download-artifact@v1
        with:
          name: release_url
      - name: Put release URL into a variable
        id: get_release_info
        run: |
          value=`cat release_url/release_url.txt`
          echo ::set-output name=upload_url::$value
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '14' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Checkout
        uses: actions/checkout@v2
      - name: Build jar
        run: mvn --no-transfer-progress clean assembly:single
      - name: Get project version
        run: echo ::set-env name=PROJECT_VERSION::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
      - name: Show project version and make build
        run: |
          echo here-it-is-$PROJECT_VERSION
          jpackage --input target/ --name Enchilada --main-jar enchilada-$PROJECT_VERSION-jar-with-dependencies.jar --icon enchilada-icon.png --app-version $PROJECT_VERSION
          ls
      - name: Get install file for Linux
        if: ${{ matrix.os =='ubuntu-latest' }}
        run: |
          echo ::set-env name=OUTPUT_FILENAME::$(ls *.deb)
      - name: Get install file for Mac
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          echo ::set-env name=OUTPUT_FILENAME::$(ls *.dmg)
      - name: Get install file for Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          echo ::set-env name=OUTPUT_FILENAME::$(ls *.exe)
      - name: Check output filename
        run: |
          echo $OUTPUT_FILENAME

      - name: Upload build to release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: ./$OUTPUT_FILENAME
          asset_name: $OUTPUT_FILENAME
          asset_content_type: application/octet-stream


