name: Run tests
on: push

defaults:
  run:
    shell: bash
jobs:
  my-build-job:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
#        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '14' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: |
            mvn --no-transfer-progress test
